# Generated by Django 2.1.5 on 2019-03-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=30)),
                ('temperature', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
