# Generated by Django 2.1.5 on 2019-03-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='my_city',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
